name:       'CSE 440'
baseurl:    '/courses/cse440/15au'

brandimage: ''
brandtext:  'CSE 440 - Introduction to HCI - Autumn 2015'

lessc: node_modules/.bin/lessc

navbar:
  items:
    - text: 'Home'
      link: 'index.html'
    - text: 'Projects'
      link: 'projects.html'
    - text: 'Calendar'
      link: 'calendar.html'

exclude:
  # Bootstrap
  - bootstrap/less
  # Node
  - node_modules
  - npm-shrinkwrap.json
  - package.json
  # Python
  - env34
  - env35
  - requirements3.txt
  - tasks.py
  - tasks.pyc
  # README
  - README.md
  # Ruby
  - Gemfile
  - Gemfile.lock
  # Tests
  - tests

collections:
  assignments:
    output: true
  projects:
    output: true
